--- title: "ST2195 Assignment 1 - R Script" output: html_document --- ## Introduction This R Markdown file contains the R script that prints all integers between 1 and 10 (including 1 and 10). ## R Script ```{r} print(1:10)
#### Jupyter Notebook
```python name=python/assignment.ipynb
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# ST2195 Assignment 1 - Python Script",
    "\n",
    "This Jupyter notebook contains the Python script that prints all integers between 1 and 10 (including 1 and 10)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "for i in range(1, 11):",
    "    print(i)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
